/**
 * Refactored preprocessing configuration system
 * Uses a step-based approach where preprocessing steps can be added dynamically
 * Each step is tracked with clear markers in the generated Python code
 */

export type PreprocessingStepType =
  | "column_filter"
  | "remove_duplicates"
  | "drop_column_or_row"
  | "drop_high_null_columns"
  | "change_dtype";

export interface PreprocessingStep {
  id: string; // Unique identifier for this step
  type: PreprocessingStepType;
  enabled: boolean;
  config: StepConfig;
}

export type StepConfig =
  | ColumnFilterStepConfig
  | RemoveDuplicatesStepConfig
  | DropColumnOrRowStepConfig
  | DropHighNullColumnsStepConfig
  | ChangeDtypeStepConfig;

export interface PreprocessingConfig {
  steps: PreprocessingStep[]; // Ordered list of preprocessing steps
}

// Column Filter Step
export interface ColumnFilterStepConfig {
  columns: ColumnFilterItem[];
}

export interface ColumnFilterItem {
  name: string;
  selected: boolean;
}

// Remove Duplicate Rows Step
export interface RemoveDuplicatesStepConfig {
  subsetColumns: string[]; // empty = compare all columns
  keep: "first" | "last";
}

// Remove Column/Row Step
export interface DropColumnOrRowStepConfig {
  target: "column" | "row";
  columns: string[]; // used when target === "column"
  rowIndices: number[]; // used when target === "row"
}

// Remove High-Null Columns Step
export interface DropHighNullColumnsStepConfig {
  thresholdPercent: number; // default 80 - columns with a higher missing % are dropped
}

// Change Column Data Type Step
export type ChangeDtypeTarget = "int" | "float" | "string" | "bool" | "datetime";

export interface ChangeDtypeItem {
  columnName: string;
  dtype: ChangeDtypeTarget;
}

export interface ChangeDtypeStepConfig {
  conversions: ChangeDtypeItem[];
}

const DTYPE_TO_PANDAS: Record<Exclude<ChangeDtypeTarget, "datetime">, string> = {
  int: "int64",
  float: "float64",
  string: "str",
  bool: "bool",
};

const PANDAS_TO_DTYPE: Record<string, Exclude<ChangeDtypeTarget, "datetime">> = {
  int64: "int",
  float64: "float",
  str: "string",
  bool: "bool",
};

/**
 * Base template for Python preprocessing code
 */
export const BASE_PYTHON_TEMPLATE = `# Generated Python function template
from typing import Optional

# Store your result in the 'result' variable
# Import any additional libraries you need
# import json
# import requests
# import datetime
import pandas as pd

# DO NOT EDIT THIS FUNCTION
def autogenerated_preprocessing_function(df):
    # STEP_MARKER_START: Preprocessing steps will be inserted here
    # STEP_MARKER_END
    return df

def executable_function(params):
    
    # This is loaded dataframe from file path:
    df = params["df"]
    # Apply the autogenerated preprocessing code
    df = autogenerated_preprocessing_function(df)

    #Write your code here

    return df`;

/**
 * Generate Python code from preprocessing configuration
 * Uses step markers to clearly identify each preprocessing step
 */
export function generatePythonCodeFromConfig(
  config: PreprocessingConfig,
  existingCode?: string
): string {
  const codeToModify = existingCode || BASE_PYTHON_TEMPLATE;

  // Find the autogenerated_preprocessing_function
  const autogenMatch = codeToModify.match(
    /def autogenerated_preprocessing_function\(df\):([\s\S]*?)(?=def |$)/
  );

  if (!autogenMatch) {
    return codeToModify;
  }

  const autogenFunctionStart = codeToModify.indexOf(autogenMatch[0]);
  const beforeAutogen = codeToModify.substring(0, autogenFunctionStart);
  const afterAutogen = codeToModify.substring(
    autogenFunctionStart + autogenMatch[0].length
  );

  // Build function body
  const autogenBodyLines: string[] = [];
  
  // Create a copy to avoid SettingWithCopyWarning
  autogenBodyLines.push("    # Create a copy to avoid SettingWithCopyWarning");
  autogenBodyLines.push("    df = df.copy()");
  autogenBodyLines.push("");

  // Generate code for each step
  config.steps.forEach((step, index) => {
    if (!step.enabled) return;

    if (index > 0 || autogenBodyLines.length > 3) {
      autogenBodyLines.push("");
    }

    // Step marker with ID and type
    autogenBodyLines.push(`    # STEP_START:${step.id}:${step.type}`);
    
    // Add minimal step configuration as JSON comment for robust parsing
    // Only store data that's ambiguous or hard to parse from code
    try {
      const minimalConfig = extractMinimalConfig(step.type, step.config);
      if (minimalConfig && Object.keys(minimalConfig).length > 0) {
        const configJson = JSON.stringify(minimalConfig);
        autogenBodyLines.push(`    # STEP_CONFIG:${configJson}`);
      }
    } catch (e) {
      console.error("Failed to serialize step config:", e);
    }
    
    switch (step.type) {
      case "column_filter":
        generateColumnFilterCode(step.config as ColumnFilterStepConfig, autogenBodyLines);
        break;
      case "remove_duplicates":
        generateRemoveDuplicatesCode(step.config as RemoveDuplicatesStepConfig, autogenBodyLines);
        break;
      case "drop_column_or_row":
        generateDropColumnOrRowCode(step.config as DropColumnOrRowStepConfig, autogenBodyLines);
        break;
      case "drop_high_null_columns":
        generateDropHighNullColumnsCode(step.config as DropHighNullColumnsStepConfig, autogenBodyLines);
        break;
      case "change_dtype":
        generateChangeDtypeCode(step.config as ChangeDtypeStepConfig, autogenBodyLines);
        break;
    }
    
    autogenBodyLines.push(`    # STEP_END:${step.id}:${step.type}`);
  });

  // If no steps, add placeholder
  if (config.steps.length === 0) {
    autogenBodyLines.push("    # No preprocessing steps configured");
  }

  autogenBodyLines.push("");
  autogenBodyLines.push("    return df");

  const newAutogenFunction = `def autogenerated_preprocessing_function(df):\n${autogenBodyLines.join("\n")}\n`;
  return beforeAutogen + newAutogenFunction + afterAutogen;
}

// Extract minimal config - only data that's ambiguous when parsing from code
function extractMinimalConfig(
  stepType: PreprocessingStepType,
  config: StepConfig
): Record<string, unknown> | null {
  switch (stepType) {
    case "column_filter": {
      const colConfig = config as ColumnFilterStepConfig;
      // Only store selected columns - can parse the rest from code
      return {
        selectedColumns: colConfig.columns
          .filter((c) => c.selected)
          .map((c) => c.name),
      };
    }
    default:
      return null;
  }
}

// Restore full config from minimal config and parsed code data
function restoreConfigFromMinimal(
  stepType: PreprocessingStepType,
  minimalConfig: Record<string, unknown>,
  parsedConfig: StepConfig | null
): StepConfig | null {
  if (!parsedConfig) return null;

  switch (stepType) {
    case "column_filter": {
      const parsed = parsedConfig as ColumnFilterStepConfig;
      const minimal = minimalConfig as { selectedColumns?: string[] };
      if (minimal.selectedColumns) {
        // Merge: use selectedColumns from minimal, keep all columns from parsed
        const selectedSet = new Set(minimal.selectedColumns);
        return {
          columns: parsed.columns.map((col) => ({
            ...col,
            selected: selectedSet.has(col.name),
          })),
        };
      }
      return parsed;
    }
    default:
      return parsedConfig;
  }
}

// Code generation helpers
function generateColumnFilterCode(
  config: ColumnFilterStepConfig,
  lines: string[]
): void {
  const selectedColumns = config.columns
      .filter((col) => col.selected && col.name.trim().length > 0)
      .map((col) => `"${col.name.trim()}"`)
      .join(", ");

    if (selectedColumns) {
    lines.push("    # Filter columns");
    lines.push(`    df = df[[${selectedColumns}]]`);
  }
}

function generateRemoveDuplicatesCode(
  config: RemoveDuplicatesStepConfig,
  lines: string[]
): void {
  const subset = (config.subsetColumns || [])
    .filter((col) => col.trim().length > 0)
    .map((col) => `"${col.trim()}"`)
    .join(", ");
  const keep = config.keep === "last" ? "last" : "first";

  lines.push("    # Remove duplicate rows");
  if (subset) {
    lines.push(`    df = df.drop_duplicates(subset=[${subset}], keep="${keep}")`);
  } else {
    lines.push(`    df = df.drop_duplicates(keep="${keep}")`);
  }
  lines.push("    df = df.reset_index(drop=True)");
}

function generateDropColumnOrRowCode(
  config: DropColumnOrRowStepConfig,
  lines: string[]
): void {
  if (config.target === "row") {
    const indices = (config.rowIndices || []).join(", ");
    if (config.rowIndices && config.rowIndices.length > 0) {
      lines.push("    # Remove row(s) by index");
      lines.push(`    df = df.drop(index=[${indices}], errors="ignore")`);
      lines.push("    df = df.reset_index(drop=True)");
    }
    return;
  }

  const columns = (config.columns || [])
    .filter((col) => col.trim().length > 0)
    .map((col) => `"${col.trim()}"`)
    .join(", ");
  if (columns) {
    lines.push("    # Remove column(s)");
    lines.push(`    df = df.drop(columns=[${columns}], errors="ignore")`);
  }
}

function generateDropHighNullColumnsCode(
  config: DropHighNullColumnsStepConfig,
  lines: string[]
): void {
  const threshold = config.thresholdPercent ?? 80;
  lines.push(`    # Remove columns with more than ${threshold}% missing values`);
  lines.push(`    df = df.loc[:, df.isnull().mean() * 100 <= ${threshold}]`);
}

function generateChangeDtypeCode(
  config: ChangeDtypeStepConfig,
  lines: string[]
): void {
  for (const item of config.conversions || []) {
    const column = (item.columnName || "").trim();
    if (!column) continue;

    lines.push(`    # Change data type of column "${column}"`);
    if (item.dtype === "datetime") {
      lines.push(`    df["${column}"] = pd.to_datetime(df["${column}"], errors="coerce")`);
    } else {
      const pandasDtype = DTYPE_TO_PANDAS[item.dtype];
      lines.push(`    df["${column}"] = df["${column}"].astype("${pandasDtype}")`);
    }
  }
}

/**
 * Parse Python code to extract preprocessing configuration
 * Uses step markers to identify and parse each step
 */
export function parsePythonCodeToConfig(code: string): PreprocessingConfig {
  const config: PreprocessingConfig = { steps: [] };

  // Extract autogenerated_preprocessing_function function body
  const autogenMatch = code.match(/def autogenerated_preprocessing_function\(df\):([\s\S]*?)(?=def |$)/);
  if (!autogenMatch) {
    return config;
  }

  const codeToParse = autogenMatch[1];

  // Find all step markers
  const stepPattern = /# STEP_START:([^:]+):([^\n]+)([\s\S]*?)# STEP_END:\1:\2/g;
  let match;
  
  while ((match = stepPattern.exec(codeToParse)) !== null) {
    const stepId = match[1];
    const stepType = match[2] as PreprocessingStepType;
    const stepCode = match[3];

    let stepConfig: StepConfig | null = null;

    // First, parse from code to get base structure
    let parsedFromCode: StepConfig | null = null;
    switch (stepType) {
      case "column_filter":
        parsedFromCode = parseColumnFilterStep(stepCode);
        break;
      case "remove_duplicates":
        parsedFromCode = parseRemoveDuplicatesStep(stepCode);
        break;
      case "drop_column_or_row":
        parsedFromCode = parseDropColumnOrRowStep(stepCode);
        break;
      case "drop_high_null_columns":
        parsedFromCode = parseDropHighNullColumnsStep(stepCode);
        break;
      case "change_dtype":
        parsedFromCode = parseChangeDtypeStep(stepCode);
        break;
    }

    // Then, try to merge with minimal config from comment if available
    const configCommentMatch = stepCode.match(/#\s*STEP_CONFIG:(.+?)(?=\n\s*#|$)/s);
    if (configCommentMatch) {
      try {
        const configJson = configCommentMatch[1].trim();
        const minimalConfig = JSON.parse(configJson) as Record<string, unknown>;
        // Restore full config by merging minimal config with parsed code
        stepConfig = restoreConfigFromMinimal(stepType, minimalConfig, parsedFromCode);
      } catch (e) {
        console.warn(`Failed to parse STEP_CONFIG for ${stepType}:`, e);
        // Fall back to parsed code only
        stepConfig = parsedFromCode;
      }
    } else {
      // No comment, use parsed code only
      stepConfig = parsedFromCode;
    }

    if (stepConfig) {
      config.steps.push({
        id: stepId,
        type: stepType,
        enabled: true, // If step marker exists, it's enabled
        config: stepConfig,
      });
    }
  }

  // Fallback: try to parse without markers (for backward compatibility)
  if (config.steps.length === 0) {
    // Try legacy parsing
    const legacyConfig = parseLegacyCode(code);
    if (legacyConfig.steps.length > 0) {
      return legacyConfig;
    }
  }

  return config;
}

// Step parsing helpers
function parseColumnFilterStep(code: string): ColumnFilterStepConfig | null {
  // Look for column filter pattern within step code
  const pattern = /df\s*=\s*df\[\[([^\]]+)\]\]/;
  const match = code.match(pattern);
  if (!match) return null;

        const columnNames = match[1]
          .split(",")
          .map((col) => col.trim().replace(/^["']|["']$/g, ""))
          .filter((col) => col.length > 0);

  if (columnNames.length === 0) return null;

  return {
    columns: columnNames.map((name) => ({ name, selected: true })),
  };
}

function parseRemoveDuplicatesStep(code: string): RemoveDuplicatesStepConfig | null {
  const match = code.match(/df\s*=\s*df\.drop_duplicates\(([^)]*)\)/);
  if (!match) return null;

  const args = match[1];
  const subsetMatch = args.match(/subset\s*=\s*\[([^\]]*)\]/);
  const keepMatch = args.match(/keep\s*=\s*["'](first|last)["']/);

  const subsetColumns = subsetMatch
    ? subsetMatch[1]
        .split(",")
        .map((col) => col.trim().replace(/^["']|["']$/g, ""))
        .filter((col) => col.length > 0)
    : [];

  return {
    subsetColumns,
    keep: keepMatch ? (keepMatch[1] as "first" | "last") : "first",
  };
}

function parseDropColumnOrRowStep(code: string): DropColumnOrRowStepConfig | null {
  const columnMatch = code.match(/df\s*=\s*df\.drop\(columns\s*=\s*\[([^\]]*)\]/);
  if (columnMatch) {
    const columns = columnMatch[1]
      .split(",")
      .map((col) => col.trim().replace(/^["']|["']$/g, ""))
      .filter((col) => col.length > 0);
    if (columns.length === 0) return null;
    return { target: "column", columns, rowIndices: [] };
  }

  const rowMatch = code.match(/df\s*=\s*df\.drop\(index\s*=\s*\[([^\]]*)\]/);
  if (rowMatch) {
    const rowIndices = rowMatch[1]
      .split(",")
      .map((v) => parseInt(v.trim(), 10))
      .filter((n) => !isNaN(n));
    if (rowIndices.length === 0) return null;
    return { target: "row", columns: [], rowIndices };
  }

  return null;
}

function parseDropHighNullColumnsStep(code: string): DropHighNullColumnsStepConfig | null {
  const match = code.match(/df\.isnull\(\)\.mean\(\)\s*\*\s*100\s*<=\s*([\d.]+)/);
  if (!match) return null;
  return { thresholdPercent: parseFloat(match[1]) };
}

function parseChangeDtypeStep(code: string): ChangeDtypeStepConfig | null {
  const conversions: ChangeDtypeItem[] = [];

  // Scan line by line (rather than one regex with a global flag) so multiple
  // conversions in a single step are collected in the order they were
  // generated in.
  for (const line of code.split("\n")) {
    const datetimeMatch = line.match(/df\["([^"]+)"\]\s*=\s*pd\.to_datetime\(df\["\1"\]/);
    if (datetimeMatch) {
      conversions.push({ columnName: datetimeMatch[1], dtype: "datetime" });
      continue;
    }

    const astypeMatch = line.match(/df\["([^"]+)"\]\s*=\s*df\["\1"\]\.astype\("([^"]+)"\)/);
    if (astypeMatch) {
      conversions.push({
        columnName: astypeMatch[1],
        dtype: PANDAS_TO_DTYPE[astypeMatch[2]] || "string",
      });
    }
  }

  if (conversions.length === 0) return null;
  return { conversions };
}

/**
 * Legacy parsing for backward compatibility
 */
function parseLegacyCode(code: string): PreprocessingConfig {
  const config: PreprocessingConfig = { steps: [] };
  // This would contain the old parsing logic as fallback
  // For now, return empty config
  return config;
}

/**
 * Create a new preprocessing step
 */
export function createPreprocessingStep(
  type: PreprocessingStepType,
  id?: string
): PreprocessingStep {
  const stepId = id || `step_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

  return {
    id: stepId,
    type,
    enabled: true,
    config: createDefaultStepConfig(type),
  };
}

function createDefaultStepConfig(type: PreprocessingStepType): StepConfig {
  switch (type) {
    case "remove_duplicates":
      return { subsetColumns: [], keep: "first" };
    case "drop_column_or_row":
      return { target: "column", columns: [], rowIndices: [] };
    case "drop_high_null_columns":
      return { thresholdPercent: 80 };
    case "change_dtype":
      return { conversions: [] };
    case "column_filter":
    default:
      return { columns: [] };
  }
}

/**
 * Get step type display name
 */
export function getStepTypeDisplayName(type: PreprocessingStepType): string {
  const names: Record<PreprocessingStepType, string> = {
    column_filter: "Column Filter",
    remove_duplicates: "Remove Duplicate Rows",
    drop_column_or_row: "Remove Column/Row",
    drop_high_null_columns: "Remove High-Null Columns",
    change_dtype: "Change Column Data Type",
  };
  return names[type] || type;
}

// Legacy config types for component compatibility
export interface ColumnFilterConfig {
  enabled: boolean;
  columns: ColumnFilterItem[];
}

